line_length:
    warning: 200
    error: 500
identifier_name:
    severity: warning
    min_length: 3
    max_length: 40
    excluded:
        - id
        - ID
        - _base
type_name:
    severity: warning
    excluded:
        - ID
force_cast:
    warning
trailing_whitespace:
    warning
force_try:
    warning
nesting:
    type_level: 2

excluded:
    - Pods
    - ../Sources/**/*/Combine
    - ../Sources/List/Shared
    - ../Sources/**/*/Basics/Shared

included:
    - ../Sources
