use_frameworks!

abstract_target 'Abstract_Example' do
  pod 'CoreRedux-Rx', :path => '../'
  pod 'CoreRedux-Rx/List', :path => '../'
  pod 'CoreBase-Rx', :path => '../'
  pod 'CoreBase-Rx/ReduxExtension', :path => '../'
  pod 'CoreList', :path => '../'
  pod 'CoreRepository-Rx', :path => '../'
  pod 'CoreAPNS-Rx', :path => '../'
  pod 'SwiftDate'
  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
  pod 'Valet'
  pod 'SwiftLint'
  
  target 'Example' do
  end

  target 'Example_Realm' do
    pod 'CoreRealmDataStore-Rx', :path => '../'
  end
  
  target 'Example_CoreData' do
    pod 'CoreDataStore-Rx', :path => '../'
  end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
