use_frameworks!

abstract_target 'Abstract_Example' do
  pod 'CoreRedux/BasicsCombine', :path => '../'
  pod 'CoreRedux/ListCombine', :path => '../'
  pod 'CoreBase/Basics', :path => '../'
  pod 'CoreBase/ReduxCombineExtension', :path => '../'
  pod 'CoreList', :path => '../'
  pod 'CoreRepository/RemoteLocalCombine', :path => '../'
  pod 'CoreAPNS/Combine', :path => '../'
  pod 'SwiftDate'
  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
  pod 'Valet'
  
  target 'Example' do
  end

  target 'Example_Realm' do
    pod 'CoreRealmDataStore/Combine', :path => '../'
  end
  
  target 'Example_CoreData' do
    pod 'CoreDataStore/Combine', :path => '../'
  end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
